#!/bin/bash

# Copyright (C) 2013 Red Hat Inc.
# SPDX-License-Identifier:	GPL-2.0+

usage()
{
  echo
  echo "Create RFRemix Live images based on Fedora 24 package base"
  echo "from internet."
  echo
  echo "create-live <imagename> <i686|x86_64|all> <version> <release> [--scratch]"
  echo "	-c - Cinnamon LiveCD"
  echo "	-w - Workstation (with GNOME) LiveCD"
  echo "	-k - KDE LiveCD"
  echo "	-x - XFCE LiveCD"
  echo "	-l - LXDE LiveCD"
  echo "	-m - MATE LiveCD"
  echo "	-a - ALL Images"
  exit 2
}

case "$1" in
  -c)
    SPINS="Cinnamon"
    ;;
  -w)
    SPINS="Workstation"
    ;;
  -t)
    SPINS="Workstation-Tigro"
    ;;
  -k)
    SPINS="KDE"
    ;;
  -x)
    SPINS="XFCE"
    ;;
  -l)
    SPINS="LXDE"
    ;;
  -m)
    SPINS="MATE_Compiz"
    ;;
  -a)
    SPINS="Workstation KDE XFCE LXDE MATE_Compiz Cinnamon"
    ;;
  *)
    usage
    ;;
esac

case "$2" in
  all)
    ARCHES="x86_64 i686"
    ;;
  i686)
    ARCHES="i686"
    ;;
  x86_64)
    ARCHES="x86_64"
    ;;
  *)
    usage
    ;;
esac

RELEASE=$3
BUILD=$4
SCRATCH=$5

if [ "x$SCRATCH" != "x" -a "x$SCRATCH" != "x--scratch" ]; then
  echo "Unknown parameter $SCRATCH"
  usage
fi

if [ "x$RELEASE" == "x" -o "x$BUILD" == "x" ]; then
  usage
fi

VERSION=$(echo $RELEASE | awk -F[_.-] '{ print $1 }')

KSEXTRAARGS="-v F21"
DEVEL=""

if [ "$VERSION" == "rawhide" ]; then
TARGET=rawhide
else
TARGET=dist-rfr$VERSION$DEVEL
fi

GITHASH=$(git rev-parse --short HEAD)

# drop url lines before build
cp spin-kickstarts/fedora-repo-not-rawhide.ks spin-kickstarts/fedora-repo-not-rawhide.ks.orig
sed -i '/^url/d' spin-kickstarts/fedora-repo-not-rawhide.ks

# define current UNIX time
DATE=$(date +%s)

for spin in $SPINS
do
    # added external repo
    declare -l lspin
    lspin=$spin
    for ARCH in $ARCHES
    do
       if [[ $ARCH == i686 ]]
         then BASEARCH=i386
         else BASEARCH=$ARCH
       fi

       ksflatten $KSEXTRAARGS -c rfremix-live-$lspin-ru_RU.ks -o rfremix-live-$lspin-$GITHASH-$DATE-ru_RU-$BASEARCH.ks >& /dev/null

       if [ "x$spin" == "xWorkstation-Tigro" ]; then
            EXTERNAL_PARAM="--repo=http://mirror.yandex.ru/fedora/linux/development/$VERSION/Everything/$BASEARCH/os/"
       else
            unset EXTERNAL_PARAM
       fi


        if [ "x$DEVEL" != "x" ]; then
            koji spin-livecd $SCRATCH --release $BUILD --skip-tag --noprogress RFRemix-Live-$spin-$ARCH $RELEASE --nowait \
                --repo=http://repos.russianfedora.pro/dist-rfr$VERSION-devel-build/latest/$BASEARCH/ \
                --repo=http://dl.fedoraproject.org/pub/fedora/linux/updates/$VERSION/$BASEARCH/ \
                --repo=http://mirror.yandex.ru/fedora/rpmfusion/free/fedora/releases/22/Everything/$BASEARCH/os/ \
                --repo=http://mirror.yandex.ru/fedora/rpmfusion/free/fedora/updates/22/$BASEARCH/ \
                --repo=http://mirror.yandex.ru/fedora/rpmfusion/free/fedora/updates/testing/23/$BASEARCH/ \
                --repo=http://mirror.yandex.ru/fedora/rpmfusion/nonfree/fedora/releases/22/Everything/$BASEARCH/os/ \
                --repo=http://mirror.yandex.ru/fedora/rpmfusion/nonfree/fedora/updates/22/$BASEARCH/ \
                --repo=http://mirror.yandex.ru/fedora/rpmfusion/nonfree/fedora/updates/testing/23/$BASEARCH/ \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/branding/fedora/development/$VERSION/$BASEARCH/os \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/fixes/fedora/development/$VERSION/$BASEARCH/os \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/development/$VERSION/$BASEARCH/os \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/development/$VERSION/$BASEARCH/os \
                $EXTERNAL_PARAM	$TARGET $ARCH rfremix-live-$lspin-$GITHASH-$DATE-ru_RU-$BASEARCH.ks
            rm -f rfremix-live-$lspin-$GITHASH-$DATE-ru_RU-$BASEARCH.ks

        else
	    koji spin-livecd $SCRATCH --release $BUILD --skip-tag --noprogress RFRemix-Live-$spin-$ARCH $RELEASE --nowait \
                --repo=http://repos.russianfedora.pro/dist-rfr$VERSION-build/latest/$BASEARCH/ \
                --repo=http://fedora.uib.no/fedora/linux/updates/24/$BASEARCH/ \
                --repo=http://mirror.yandex.ru/fedora/rpmfusion/free/fedora/updates/testing/$VERSION/$BASEARCH/ \
                --repo=http://mirror.yandex.ru/fedora/rpmfusion/nonfree/fedora/updates/testing/$VERSION/$BASEARCH/ \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/branding/fedora/releases/$VERSION/Everything/$BASEARCH/os \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/branding/fedora/updates/$VERSION/$BASEARCH \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/fixes/fedora/releases/$VERSION/Everything/$BASEARCH/os \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/fixes/fedora/updates/$VERSION/$BASEARCH \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/releases/$VERSION/Everything/$BASEARCH/os \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/updates/$VERSION/$BASEARCH \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/releases/$VERSION/Everything/$BASEARCH/os \
                --repo=http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/updates/$VERSION/$BASEARCH \
                $EXTERNAL_PARAM $TARGET $ARCH rfremix-live-$lspin-$GITHASH-$DATE-ru_RU-$BASEARCH.ks
            rm -f rfremix-live-$lspin-$GITHASH-$DATE-ru_RU-$BASEARCH.ks
       fi
   done
done

mv spin-kickstarts/fedora-repo-not-rawhide.ks.orig spin-kickstarts/fedora-repo-not-rawhide.ks
