#!/bin/sh

usage()
{
    echo
    echo "mere-repos --stage <stage> --ver <version>"
    echo
    echo "           stage: stable, devel, rawhide"
    echo
    exit 1
}

while [ $# -gt 0 ]; do
  case $1 in
    --stage)
      STAGE=$2
      shift; shift
    ;;
    --ver)
      VERSION=$2
      shift; shift
    ;;
    *)
      echo "Unknown parameter. Abort..."
      usage
    ;;
  esac
done

if [ "$STAGE" != "stable" -a "$STAGE" != "devel" -a "$STAGE" != "rawhide" ]; then
    echo "Unknown stage. Abort..."
    usage
fi

if [ "x$VERSION" == "x" -a "$STAGE" != "rawhide" ]; then
    echo "Unknown version. Abort..."
    usage
fi

if [ "$STAGE" == "rawhide" ]; then
    VERSION="rawhide"
    KOJI_REPO_NAME="dist-rfr-rawhide-build"
    COMPS_VERSION="25"
    GIT_VERSION="master"
elif [ "$STAGE" == "devel" ]; then
    KOJI_REPO_NAME="dist-rfr$VERSION-devel-build"
    COMPS_VERSION="$VERSION"
    GIT_VERSION="f$VERSION/master"
fi

BASEARCH="x86_64"

if [ "$STAGE" == "devel" -o "$STAGE" == "rawhide" ]; then
    rm -rf comps
    git clone -b $GIT_VERSION git://github.com/RussianFedora/russianfedora-comps.git comps/

    COMPS_URL="ftp://mirror.yandex.ru/fedora/linux/development/$VERSION/Everything/x86_64/os/repodata/"
    
    curl -LJ -o comps/fedora.xml $COMPS_URL$(curl -s $COMPS_URL | grep comps | awk '/\.xml$/ { print $NF }')

    yum-groups-manager --disablerepo='*' --config=/etc/yum.conf \
        $(find comps/ -type f -name "*.xml" | sed 's@^@--load=@g') --save $KOJI_REPO_NAME.xml -n base
fi
